hackmdPostgres:
  image: postgres
  volumes:
    - /share/etc/hackmd/postgresql/data:/var/lib/postgresql/data
  environment:
    - POSTGRES_USER=hackmd
    - POSTGRES_PASSWORD=hackmdpass
    - POSTGRES_DB=hackmd
hackmd:
  image: hackmdio/hackmd:latest
  environment:
    - POSTGRES_USER=hackmd
    - POSTGRES_PASSWORD=hackmdpass
  links:
    - hackmdPostgres:hackmdPostgres
  ports:
    - "3000:3000"
